
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS product_attributes;
DROP TABLE IF EXISTS product_images;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS attributes;
DROP TABLE IF EXISTS categories;

SET FOREIGN_KEY_CHECKS = 1;
